---
title: "P_2.2"
output: html_document
date: "2023-09-23"
---

```{r}
library(tidyr)
library(dplyr)
```

```{r}
rairuoho <- read.table('https://www.dipintothereef.com/uploads/3/7/3/5/37359245/rairuoho.txt', header =T, sep="\t")
# use the URL instead. When a file is available online it saves your time to import directly from a URL
# if you use a local file like you ar doing here, better to create another file such as 'Data' in your working directory. To import it you will use: 'Data/rairuoho.txt'
# don't forget header = T. That's why you have to do some of the steps below.

```

```{r}
# better to call variable name after importing the file with header = T
rairuoho["treatment"][rairuoho["treatment"] == 'nutrient'] <- "enriched"
```

```{r}
rairuoho2 <- rairuoho[, -12]
rairuoho3 <- rairuoho2[, -12]
```

```{r}
rairuoho3 <- rairuoho3[-1,] # this step in uncessary if header=T when you import your file
```

```{r}
#rairuoho3 <- rairuoho3 %>% 
    #rename("day3" = "V1", "day4" = "V2", "day5" = "V3", "day6" = "V4", "day7" = "V5", "day8" = "V6", "germinate" = "V7", "bed" = "V8", "treatment" = "V9", "spatial1" = "V10", "spatial2" = "V11")
```

```{r}
rairuoho_long <- rairuoho3 %>% pivot_longer(day3:day8, names_to = "factor", values_to = "length")
```

```{r}
rairuoho_long2 <- rairuoho_long %>% unite("spatial", spatial1:spatial2)
```

```{r}
print(rairuoho_long2)
```

Overall, you made it. Good job.
